In [1]:
a = 10
type(a)

int

In [2]:
a.bit_length()

4

In [3]:
a = 100000
a.bit_length()

17

In [11]:
googol = 10 ** 100
googol

10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000L

In [12]:
googol.bit_length()

333

## Integer

In [20]:
1/4

0

In [21]:
type(1/4)

int

## Float

In [23]:
1./4

0.25

In [24]:
type(1./4)

float

In [25]:
b = 0.35
type(b)

float

In [26]:
b + 0.1

0.44999999999999996

In [27]:
c = 0.5
c.as_integer_ratio()

(1, 2)

## Decimal

In [30]:
import decimal
from decimal import Decimal

In [32]:
decimal.getcontext()

Context(prec=28, rounding=ROUND_HALF_EVEN, Emin=-999999999, Emax=999999999, capitals=1, flags=[Inexact, Rounded], traps=[InvalidOperation, Overflow, DivisionByZero])

In [31]:
d = Decimal(1) / Decimal (11)
d

Decimal('0.09090909090909090909090909091')

In [33]:
decimal.getcontext().prec = 4  # lower precision than default

In [34]:
e = Decimal(1) / Decimal (11)
e

Decimal('0.09091')

## STRINGS

In [35]:
t = 'this is a string object'

In [36]:
t.capitalize() # capitalize the first word in this object

'This is a string object'

In [38]:
t.split() # split it into its single-word components to get a list object of all the word

['this', 'is', 'a', 'string', 'object']

In [39]:
t.find('string') # search for a word, get the position (index value) of the first letter of the word back in a successful case

10

In [40]:
t.find('Python') # If the word is not in the string object, the method returns -1

-1

In [41]:
t.replace(' ', '|') # Replacing characters in a string is a typical task that is easily accomplished with the replace method

'this|is|a|string|object'

In [42]:
'http://www.python.org'.strip('htp:/')

'www.python.org'

In [1]:
import re
series = """
'01/18/2014 13:00:00', 100, '1st';
'01/18/2014 13:30:00', 110, '2nd';
'01/18/2014 14:00:00', 120, '3rd'
"""

In [2]:
dt = re.compile("'[0-9/:\s]+'")  # datetime

In [3]:
result = dt.findall(series)
result

["'01/18/2014 13:00:00'", "'01/18/2014 13:30:00'", "'01/18/2014 14:00:00'"]

In [4]:
series

"\n'01/18/2014 13:00:00', 100, '1st';\n'01/18/2014 13:30:00', 110, '2nd';\n'01/18/2014 14:00:00', 120, '3rd'\n"

In [7]:
from datetime import datetime
pydt = datetime.strptime(result[0].replace("'", ""),
                         '%m/%d/%Y %H:%M:%S')
pydt

datetime.datetime(2014, 1, 18, 13, 0)

In [8]:
print pydt

2014-01-18 13:00:00


In [9]:
print type(pydt)

<type 'datetime.datetime'>


## TUPLES

In [10]:
t = (1, 2.5, 'data')
type(t)

tuple

In [11]:
 t = 1, 2.5, 'data'
type(t)

tuple

In [12]:
t[2]

'data'

In [13]:
type(t[2])

str

In [14]:
t.count('data')

1

In [15]:
t.index(1)

0

## LISTS

In [16]:
l = [1, 2.5, 'data']
l[2]

'data'

In [17]:
l = list(t)
l

[1, 2.5, 'data']

In [18]:
type(l)

list

In [19]:
l.append([4, 3])  # append list at the end
l

[1, 2.5, 'data', [4, 3]]

In [20]:
l.extend([1.0, 1.5, 2.0])  # append elements of list
l

[1, 2.5, 'data', [4, 3], 1.0, 1.5, 2.0]

In [21]:
l.insert(1, 'insert')  # insert object before index position
l

[1, 'insert', 2.5, 'data', [4, 3], 1.0, 1.5, 2.0]

In [22]:
l.remove('data')  # remove first occurrence of object
l

[1, 'insert', 2.5, [4, 3], 1.0, 1.5, 2.0]

In [23]:
p = l.pop(3)  # removes and returns object at index
print l, p

[1, 'insert', 2.5, 1.0, 1.5, 2.0] [4, 3]


In [24]:
l[2:5]

[2.5, 1.0, 1.5]

# EXCURSION
## ## CONTROL STRUCTURES

## Loops

In [25]:
for element in l[2:5]:
             print element ** 2

6.25
1.0
2.25


In [27]:
r = range(0, 8, 1)  # start, end, step width
r

[0, 1, 2, 3, 4, 5, 6, 7]

In [28]:
type(r)

list

In [30]:
for i in range(2, 5):
    print l[i] ** 2

6.25
1.0
2.25


In [34]:
for i in range(1, 10):
    if i % 2 == 0:  # % is for modulo
        print "%d is even" % i
    elif i % 3 == 0:
        print "%d is multiple of 3" % i
    else:
        print "%d is odd" % i

1 is odd
2 is even
3 is multiple of 3
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is multiple of 3


In [40]:
total = 0
while total < 100:
    total += 1
print total

100


In [41]:
m = [i ** 2 for i in range(5)]
m

[0, 1, 4, 9, 16]

## FUNCTIONAL PROGRAMMING

In [47]:
def f(x):
    return x ** 2
f(2)

4

In [48]:
def even(x):
    return x % 2 == 0
even(3)

False

In [49]:
map(even, range(10))

[True, False, True, False, True, False, True, False, True, False]

In [50]:
 map(lambda x: x ** 2, range(10))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [51]:
filter(even, range(15))

[0, 2, 4, 6, 8, 10, 12, 14]

In [52]:
reduce(lambda x, y: x + y, range(10))

45

####  non-functional implementation

In [53]:
def cumsum(l):
    total = 0
    for elem in l:
        total += elem
    return total
cumsum(range(10))

45

## DICTS

In [63]:
d = {
    'Name' : 'Angela Merkel',
    'Country' : 'Germany',
    'Profession' : 'Chancelor',
    'Age' : 60
}
type(d)

dict

In [55]:
print d['Name'], d['Age']

Angela Merkel 60


In [56]:
d.keys()

['Country', 'Age', 'Profession', 'Name']

In [57]:
d.values()

['Germany', 60, 'Chancelor', 'Angela Merkel']

In [64]:
d.items()

[('Country', 'Germany'),
 ('Age', 60),
 ('Profession', 'Chancelor'),
 ('Name', 'Angela Merkel')]

In [65]:
birthday = True
if birthday is True:
    d['Age'] += 1
print d['Age']

61


In [66]:
for item in d.iteritems():
    print item

('Country', 'Germany')
('Age', 61)
('Profession', 'Chancelor')
('Name', 'Angela Merkel')


In [68]:
for value in d.itervalues():
    print type(value)

<type 'str'>
<type 'int'>
<type 'str'>
<type 'str'>


## SETS

In [69]:
s = set(['u', 'd', 'ud', 'du', 'd', 'du'])
s

{'d', 'du', 'u', 'ud'}

In [70]:
s.union(t)  # all of s and t

{1, 2.5, 'd', 'data', 'du', 'u', 'ud'}

In [71]:
s.intersection(t)

set()

In [72]:
s.difference(t)

{'d', 'du', 'u', 'ud'}

In [74]:
s.symmetric_difference(t)  # in either one but not both

{1, 2.5, 'd', 'data', 'du', 'u', 'ud'}

In [75]:
from random import randint
l = [randint(0, 10) for i in range(1000)]
     # 1,000 random integers between 0 and 10
len(l)  # number of elements in l

1000

In [76]:
l[:20]

[4, 6, 7, 5, 6, 8, 7, 6, 9, 4, 1, 9, 10, 3, 1, 1, 6, 8, 8, 6]

In [79]:
s = set(l)
s

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

# NumPy Data Structures

## ARRAYS WITH PYTHON LISTS

In [80]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]  # vector of numbers

In [81]:
m = [v, v, v]  # matrix of numbers
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [82]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [83]:
m[1][0]

0.5

In [84]:
v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m]  # cube of numbers
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [85]:
c[1][1][0]

1

In [86]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [87]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [88]:
from copy import deepcopy
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v), ]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [89]:
v[0] = 'Python'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

## REGULAR NUMPY ARRAYs

In [90]:
import numpy as np
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
type(a)

numpy.ndarray

In [91]:
a[:2]  # indexing as with list objects in 1 dimension

array([0. , 0.5])

In [92]:
a.sum()  # sum of all elements

5.0

In [93]:
a.std()  # standard deviation

0.7071067811865476

In [94]:
a.cumsum()  # running cumulative sum

array([0. , 0.5, 1.5, 3. , 5. ])

In [95]:
a * 2

array([0., 1., 2., 3., 4.])

In [96]:
a ** 2

array([0.  , 0.25, 1.  , 2.25, 4.  ])

In [97]:
np.sqrt(a)

array([0.        , 0.70710678, 1.        , 1.22474487, 1.41421356])

In [98]:
b = np.array([a, a * 2])
b

array([[0. , 0.5, 1. , 1.5, 2. ],
       [0. , 1. , 2. , 3. , 4. ]])

In [99]:
b[0]  # first row

array([0. , 0.5, 1. , 1.5, 2. ])

In [100]:
b[0, 2]  # third element of first row

1.0

In [101]:
b.sum()

15.0

In [102]:
b.sum(axis=0)

array([0. , 1.5, 3. , 4.5, 6. ])

In [103]:
b.sum(axis=1)

array([ 5., 10.])

In [104]:
c = np.zeros((2, 3, 4), dtype='i', order='C')  # also: np.ones()
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [113]:
d = np.ones_like(c, dtype='float64' , order='C')  # also: np.zeros_like()
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [116]:
import random
I = 5000
%time mat = [[random.gauss(0, 1) for j in range(I)] for i in range(I)] # a nested list comprehension

Wall time: 1min 30s


In [115]:
 %time reduce(lambda x, y: x + y,      \
              [reduce(lambda x, y: x + y, row) \
               for row in mat])

Wall time: 6.95 s


352.26314978335677

In [125]:
 %time mat = np.random.standard_normal((I, I))

Wall time: 2.5 s


In [126]:
%time mat.sum()

Wall time: 115 ms


2957.908111812312

## STRUCTURED ARRAYS

In [127]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'),
               ('Height', 'f'), ('Children/Pets', 'i4', 2)])
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)
s

array([('Smith', 45, 1.83, [0, 1]), ('Jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [128]:
s['Name']

array(['Smith', 'Jones'], dtype='|S10')

In [129]:
s['Height'].mean()

1.7750001

In [130]:
s[1]['Age']

53

# Vectorization of Code
## Basic Vectorization

In [132]:
r = np.random.standard_normal((4, 3))
s = np.random.standard_normal((4, 3))

In [133]:
r + s

array([[-3.37056276, -1.96800578,  0.71232148],
       [-1.12708595,  1.62913059,  0.30735717],
       [ 0.1603932 ,  2.45389054,  0.42095855],
       [ 0.46247927,  0.99154043,  0.92775631]])

In [134]:
2 * r + 3

array([[ 0.67033935, -0.95625336,  3.56075407],
       [ 2.171074  ,  4.02608181,  4.66347776],
       [ 3.41717761,  5.01025282,  4.81262843],
       [ 5.34202655,  6.07302074,  3.67671193]])

In [135]:
s = np.random.standard_normal(3)
r + s

array([[-1.24039625, -1.77790045,  0.54683963],
       [-0.49002892,  0.71326714,  1.09820148],
       [ 0.13302288,  1.20535264,  1.17277681],
       [ 1.09544735,  1.7367366 ,  0.60481856]])

In [136]:
s = np.random.standard_normal(4)
r + s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [137]:
r.transpose() + s

array([[-1.37340969, -1.76344165, -1.12582656, -0.1504486 ],
       [-2.18670604, -0.83593774, -0.32928895,  0.21504849],
       [ 0.07179768, -0.51723977, -0.42810115, -0.98310591]])

In [138]:
np.shape(r.T)

(3L, 4L)

In [140]:
def f(x):
    return 3 * x + 5

In [141]:
f(0.5)  # float object

6.5

In [142]:
f(r)  # NumPy array

array([[ 1.50550902, -0.93438004,  5.84113111],
       [ 3.756611  ,  6.53912272,  7.49521664],
       [ 5.62576641,  8.01537923,  7.71894265],
       [ 8.51303982,  9.6095311 ,  6.01506789]])

In [144]:
import math
math.sin(r)

TypeError: only size-1 arrays can be converted to Python scalars

In [145]:
np.sin(r)  # array as input

array([[-0.91872135, -0.9181817 ,  0.27671798],
       [-0.40269846,  0.49082892,  0.73910378],
       [ 0.2070795 ,  0.84422973,  0.78723625],
       [ 0.92114546,  0.99941229,  0.33193672]])

In [146]:
np.sin(np.pi)  # float as input

1.2246467991473532e-16

# MEMORY LAYOUT

In [ ]:
x = np.random.standard_normal((5, 10000000))
y = 2 * x + 3  # linear equation y = a * x + b
C = np.array((x, y), order='C')
F = np.array((x, y), order='F')
x = 0.0; y = 0.0  # memory cleanup

In [148]:
C[:2].round(2)

array([[[ 1.02,  1.22,  1.86, ...,  0.59,  1.01,  0.33],
        [ 1.21, -0.75,  0.33, ...,  0.7 ,  0.35,  0.8 ],
        [ 0.6 , -1.03, -0.14, ..., -2.02,  0.82,  0.56],
        [-1.37, -0.97,  0.68, ..., -0.12, -0.77, -0.23],
        [ 1.17, -0.41,  1.39, ...,  1.3 ,  0.17,  1.61]],

       [[ 5.03,  5.44,  6.73, ...,  4.19,  5.01,  3.65],
        [ 5.43,  1.5 ,  3.67, ...,  4.4 ,  3.71,  4.6 ],
        [ 4.19,  0.94,  2.72, ..., -1.04,  4.64,  4.11],
        [ 0.26,  1.06,  4.36, ...,  2.75,  1.46,  2.53],
        [ 5.33,  2.18,  5.78, ...,  5.59,  3.33,  6.22]]])

In [149]:
%timeit C.sum()

1 loop, best of 3: 456 ms per loop


In [150]:
%timeit F.sum()

1 loop, best of 3: 459 ms per loop


In [151]:
%timeit C[0].sum(axis=0)

1 loop, best of 3: 292 ms per loop


In [152]:
%timeit C[0].sum(axis=1)

1 loop, best of 3: 225 ms per loop


In [153]:
%timeit F.sum(axis=0)

1 loop, best of 3: 1.99 s per loop


In [154]:
%timeit F.sum(axis=1)

1 loop, best of 3: 5.07 s per loop


In [155]:
F = 0.0; C = 0.0  # memory cleanup